services:
  web:
    build: .
    ports:
      - "5001:5000"
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://degel55:Frunkuss55!@192.168.0.206:5432/epl_predictor
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: degel55
      POSTGRES_PASSWORD: Frunkuss55!
      POSTGRES_DB: epl_predictor
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: